#!/bin/bash
#
# bootstrap installs things.
# Idempotent: safe to re-run if interrupted.

DOTFILES_ROOT="`pwd`"

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
}

# Run a command, continue on failure
run () {
  "$@" 2>&1 && return 0
  fail "$*"
  return 1
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]; then
    info 'setup gitconfig'
    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink
    success 'gitconfig'
  else
    info 'gitconfig already exists, skipping'
    success 'gitconfig'
  fi
}

link_files () {
  ln -s "$1" "$2"
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f "$dest" ] || [ -d "$dest" ]; then
      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action
        echo ''

        case "$action" in
          o) overwrite=true;;
          O) overwrite_all=true;;
          b) backup=true;;
          B) backup_all=true;;
          s) skip=true;;
          S) skip_all=true;;
          *) ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]; then
        rm -rf "$dest"
        success "removed $dest"
        link_files "$source" "$dest"
      elif [ "$backup" == "true" ] || [ "$backup_all" == "true" ]; then
        mv "$dest" "$dest.backup"
        success "moved $dest to $dest.backup"
        link_files "$source" "$dest"
      elif [ "$skip" == "false" ] && [ "$skip_all" == "false" ]; then
        link_files "$source" "$dest"
      else
        success "skipped $source"
      fi
    else
      link_files "$source" "$dest"
    fi
  done
}

install_homebrew() {
  if ! command -v brew >/dev/null 2>&1; then
    info "Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    success 'homebrew'
  else
    info 'homebrew already installed, skipping'
    success 'homebrew'
  fi
}

install_oh_my_zsh() {
  if ! [ -d "$HOME/.oh-my-zsh" ]; then
    info "Install Oh My Zsh"
    run sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  else
    info 'oh-my-zsh already installed, skipping'
    success 'oh-my-zsh'
  fi
}

install_pyenv() {
  if ! [ -d "$HOME/.pyenv" ]; then
    info "Install pyenv"
    run git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
    success 'pyenv'
  else
    info 'pyenv already installed, skipping'
    success 'pyenv'
  fi
}

install_jenv() {
  if ! [ -d "$HOME/.jenv" ]; then
    info "Install jenv"
    run git clone https://github.com/jenv/jenv.git "$HOME/.jenv"
    success 'jenv'
  else
    info 'jenv already installed, skipping'
    success 'jenv'
  fi
}

install_nvm() {
  if ! [ -f "$HOME/.nvm/nvm.sh" ]; then
    info "Install NVM"
    run curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    success 'nvm'
  else
    info 'nvm already installed, skipping'
    success 'nvm'
  fi
}

install_tmux_plugins() {
  if ! [ -f "$HOME/.tmux/plugins/tpm/tpm" ]; then
    info "Install TPM"
    run git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    success 'tpm'
  else
    info 'tpm already installed, skipping'
    success 'tpm'
  fi
}

install_via_brew() {
  info "Install packages via brew"

  for pkg in z git-extras newman; do
    if brew list "$pkg" >/dev/null 2>&1; then
      info "  $pkg already installed, skipping"
    else
      info "  installing $pkg"
      brew install "$pkg" && success "  $pkg installed" || fail "  $pkg failed"
    fi
  done
}

# Run installations in order
setup_gitconfig
install_dotfiles
install_homebrew
install_oh_my_zsh
install_pyenv
install_jenv
install_nvm
install_tmux_plugins
install_via_brew

echo ''
echo '  All installed!'
