#!/bin/bash
#
# bootstrap installs things.
# Idempotent: safe to re-run if interrupted.

DOTFILES_ROOT="`pwd`"

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
}

# Run a command, continue on failure
run () {
  "$@" 2>&1 && return 0
  fail "$*"
  return 1
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]; then
    info 'setup gitconfig'
    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink
    success 'gitconfig'
  else
    info 'gitconfig already exists, skipping'
    success 'gitconfig'
  fi
}

link_files () {
  ln -s "$1" "$2"
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f "$dest" ] || [ -d "$dest" ]; then
      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action
        echo ''

        case "$action" in
          o) overwrite=true;;
          O) overwrite_all=true;;
          b) backup=true;;
          B) backup_all=true;;
          s) skip=true;;
          S) skip_all=true;;
          *) ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]; then
        rm -rf "$dest"
        success "removed $dest"
        link_files "$source" "$dest"
      elif [ "$backup" == "true" ] || [ "$backup_all" == "true" ]; then
        mv "$dest" "$dest.backup"
        success "moved $dest to $dest.backup"
        link_files "$source" "$dest"
      elif [ "$skip" == "false" ] && [ "$skip_all" == "false" ]; then
        link_files "$source" "$dest"
      else
        success "skipped $source"
      fi
    else
      link_files "$source" "$dest"
    fi
  done
}

install_tmux_conf_local() {
  if ! [ -f "$HOME/.tmux.conf.local" ]; then
    info "Create ~/.tmux.conf.local"
    touch "$HOME/.tmux.conf.local"
    success 'tmux.conf.local'
  fi
}

install_homebrew() {
  if ! command -v brew >/dev/null 2>&1; then
    info "Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    success 'homebrew'
  else
    info 'homebrew already installed, skipping'
    success 'homebrew'
  fi
}

install_oh_my_zsh() {
  if ! [ -d "$HOME/.oh-my-zsh" ]; then
    info "Install Oh My Zsh"
    run sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  else
    info 'oh-my-zsh already installed'
    user " - Upgrade oh-my-zsh? [y/N]:"
    read confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      (cd "$HOME/.oh-my-zsh" && git pull origin master)
      success 'oh-my-zsh upgraded'
    else
      success 'oh-my-zsh skipped'
    fi
  fi
}

install_pyenv() {
  if ! [ -d "$HOME/.pyenv" ]; then
    info "Install pyenv"
    run git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
    success 'pyenv'
  else
    info 'pyenv already installed'
    user " - Upgrade pyenv? [y/N]:"
    read confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      (cd "$HOME/.pyenv" && git pull origin master)
      success 'pyenv upgraded'
    else
      success 'pyenv skipped'
    fi
  fi
}

install_pyenv_virtualenv() {
  if ! [ -d "$HOME/.pyenv/plugins/pyenv-virtualenv" ]; then
    info "Install pyenv-virtualenv"
    run git clone https://github.com/pyenv/pyenv-virtualenv.git "$HOME/.pyenv/plugins/pyenv-virtualenv"
    success 'pyenv-virtualenv'
  else
    info 'pyenv-virtualenv already installed'
    user " - Upgrade pyenv-virtualenv? [y/N]:"
    read confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      (cd "$HOME/.pyenv/plugins/pyenv-virtualenv" && git pull origin master)
      success 'pyenv-virtualenv upgraded'
    else
      success 'pyenv-virtualenv skipped'
    fi
  fi
}

setup_python_env() {
  info "Setup Python environment"

  # Check if pyenv is available
  if ! command -v pyenv >/dev/null 2>&1; then
    info "pyenv not in PATH, skipping Python setup"
    return 0
  fi

  # Show current Python environment status
  if [ -n "$(pyenv versions --bare 2>/dev/null)" ]; then
    info "Installed Python versions:"
    pyenv versions --bare 2>/dev/null | while read v; do
      info "  - $v"
    done
  fi

  local current_py=$(pyenv global 2>/dev/null)
  if [ -n "$current_py" ] && [ "$current_py" != "system" ]; then
    info "Current global Python: $current_py"
  fi

  # Show existing virtualenvs
  if [ -d "$HOME/.pyenv/versions" ]; then
    local venvs=$(pyenv virtualenvs --bare 2>/dev/null)
    if [ -n "$venvs" ]; then
      info "Existing virtualenvs:"
      echo "$venvs" | while read v; do
        info "  - $v"
      done
    fi
  fi

  # Check if already has a global Python set up
  if [ -n "$current_py" ] && [ "$current_py" != "system" ]; then
    user " - Python $current_py already configured. Install new version? [y/N]:"
    read confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
      info "Keeping existing Python setup"
      return 0
    fi
  fi

  # List available Python versions
  info "Available Python versions:"
  pyenv install --list 2>/dev/null | grep -E "^\s*[0-9]+\.[0-9]+\.[0-9]+" | head -10

  user " - Enter Python version to install (e.g., 3.12.0) or press Enter to skip:"
  read python_version

  if [ -n "$python_version" ]; then
    # Check if already installed
    if pyenv versions --bare 2>/dev/null | grep -q "^${python_version}$"; then
      info "Python $python_version already installed"
    else
      info "Installing Python $python_version"
      if pyenv install "$python_version" 2>&1; then
        success "Python $python_version installed"
      else
        fail "Failed to install Python $python_version"
        return 1
      fi
    fi

    # Set global Python version
    pyenv global "$python_version"
    success "Set global Python to $python_version"

    # Create default virtualenv (optional)
    user " - Enter virtualenv name to create (or press Enter to skip):"
    read venv_name
    if [ -n "$venv_name" ]; then
      # Check if virtualenv already exists
      if pyenv virtualenvs --bare 2>/dev/null | grep -q "^${venv_name}$"; then
        info "Virtualenv $venv_name already exists, skipping"
      else
        pyenv virtualenv "$python_version" "$venv_name"
        success "Created virtualenv: $venv_name"
      fi
    fi
  else
    info "Skipping Python installation"
  fi
}

install_jenv() {
  if ! [ -d "$HOME/.jenv" ]; then
    info "Install jenv"
    run git clone https://github.com/jenv/jenv.git "$HOME/.jenv"
    success 'jenv'
  else
    info 'jenv already installed'
    user " - Upgrade jenv? [y/N]:"
    read confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      (cd "$HOME/.jenv" && git pull origin master)
      success 'jenv upgraded'
    else
      success 'jenv skipped'
    fi
  fi
}

install_nvm() {
  if ! [ -f "$HOME/.nvm/nvm.sh" ]; then
    info "Install NVM"
    run curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    success 'nvm'
  else
    info 'nvm already installed'
    user " - Reinstall/upgrade NVM? [y/N]:"
    read confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      run curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
      success 'nvm upgraded'
    else
      success 'nvm skipped'
    fi
  fi
}

install_tmux_plugins() {
  if ! [ -f "$HOME/.tmux/plugins/tpm/tpm" ]; then
    info "Install TPM"
    run git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    success 'tpm'
  else
    info 'tpm already installed'
    user " - Upgrade TPM? [y/N]:"
    read confirm
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
      (cd "$HOME/.tmux/plugins/tpm" && git pull origin master)
      success 'tpm upgraded'
    else
      success 'tpm skipped'
    fi
  fi
}

install_via_brew() {
  info "Install packages via brew"

  for pkg in z git-extras newman; do
    if brew list "$pkg" >/dev/null 2>&1; then
      info "  $pkg already installed, skipping"
    else
      info "  installing $pkg"
      brew install "$pkg" && success "  $pkg installed" || fail "  $pkg failed"
    fi
  done
}

# Run installations in order
setup_gitconfig
install_dotfiles
install_tmux_conf_local
install_homebrew
install_oh_my_zsh
install_pyenv
install_pyenv_virtualenv
setup_python_env
install_jenv
install_nvm
install_tmux_plugins
install_via_brew

echo ''
echo '  All installed!'
